package com.dragonminez.common.config;

import com.dragonminez.Env;
import com.dragonminez.LogUtil;
import com.dragonminez.common.util.lists.*;
import com.google.gson.Gson;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;

public class DefaultFormsFactory {

    private final ConfigLoader loader;

    public DefaultFormsFactory(Gson gson, ConfigLoader loader) {
        this.loader = loader;
    }

    private void setDefaultMasteryValues(FormConfig.FormData form) {
        form.setMaxMastery(100.0);
        form.setMasteryPerHit(0.05);
        form.setMasteryPerDamageReceived(0.05);
        form.setStatMultPerMasteryPoint(0.02);
        form.setCostDecreasePerMasteryPoint(0.02);
    }

    public void createDefaultFormsForRace(String raceName, Path formsPath, Map<String, FormConfig> forms) throws IOException {
        switch (raceName.toLowerCase()) {
			case "human" -> createDefaultHumanForms(formsPath, forms);
            case "saiyan" -> createSaiyanForms(formsPath, forms);
            case "namekian" -> createNamekianForms(formsPath, forms);
            case "frostdemon" -> createFrostDemonForms(formsPath, forms);
            case "majin" -> createMajinForms(formsPath, forms);
            case "bioandroid" -> createBioAndroidForms(formsPath, forms);
        }
    }

	private void createDefaultHumanForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig humanForms = new FormConfig();
        humanForms.setGroupName(HumanForms.GROUP_SUPERFORMS);
        humanForms.setFormType("super");

        FormConfig.FormData buffed = new FormConfig.FormData();
        buffed.setName(HumanForms.BUFFED);
        buffed.setUnlockOnSkillLevel(1);
        buffed.setCustomModel("");
        buffed.setModelScaling(new float[]{1.2f, 1.1f, 1.2f});
        buffed.setStrMultiplier(1.5);
        buffed.setSkpMultiplier(1.65);
        buffed.setStmMultiplier(1.0);
        buffed.setDefMultiplier(1.25);
        buffed.setVitMultiplier(1.0);
        buffed.setPwrMultiplier(1.35);
        buffed.setEneMultiplier(1.0);
        buffed.setSpeedMultiplier(1.0);
        buffed.setEnergyDrain(0.08);
        buffed.setStaminaDrain(1.0);
        buffed.setAttackSpeed(1.0);
        buffed.setHairColor("");
        buffed.setEye1Color("");
        buffed.setEye2Color("");
        buffed.setAuraColor("");
		buffed.setHasLightnings(false);
		buffed.setLightningColor("");
        buffed.setBodyColor1("");
        buffed.setBodyColor2("");
        buffed.setBodyColor3("");
		buffed.setHairType("base");
        buffed.setForcedHairCode("");
        setDefaultMasteryValues(buffed);
        buffed.setKaiokenStackable(true);
        buffed.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fullPower = new FormConfig.FormData();
        fullPower.setName(HumanForms.FULLPOWER);
        fullPower.setUnlockOnSkillLevel(2);
        fullPower.setCustomModel("");
        fullPower.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        fullPower.setStrMultiplier(1.75);
        fullPower.setSkpMultiplier(2.0);
        fullPower.setStmMultiplier(1.0);
        fullPower.setDefMultiplier(1.65);
        fullPower.setVitMultiplier(1.0);
        fullPower.setPwrMultiplier(1.5);
        fullPower.setEneMultiplier(1.0);
        fullPower.setSpeedMultiplier(1.0);
        fullPower.setEnergyDrain(0.16);
        fullPower.setStaminaDrain(1.0);
        fullPower.setAttackSpeed(1.0);
        fullPower.setHairColor("");
        fullPower.setEye1Color("");
        fullPower.setEye2Color("");
        fullPower.setAuraColor("");
		fullPower.setHasLightnings(false);
		fullPower.setLightningColor("");
        fullPower.setBodyColor1("");
        fullPower.setBodyColor2("");
        fullPower.setBodyColor3("");
		fullPower.setHairType("ssj");
        fullPower.setForcedHairCode("");
        setDefaultMasteryValues(fullPower);
        fullPower.setKaiokenStackable(true);
        fullPower.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData overdrive = new FormConfig.FormData();
        overdrive.setName(HumanForms.OVERDRIVE);
        overdrive.setUnlockOnSkillLevel(3);
        overdrive.setCustomModel("");
        overdrive.setModelScaling(new float[]{1.1f, 1.1f, 1.1f});
        overdrive.setStrMultiplier(3.0);
        overdrive.setSkpMultiplier(3.35);
        overdrive.setStmMultiplier(1.0);
        overdrive.setDefMultiplier(2.15);
        overdrive.setVitMultiplier(1.0);
        overdrive.setPwrMultiplier(2.65);
        overdrive.setEneMultiplier(1.0);
        overdrive.setSpeedMultiplier(1.0);
        overdrive.setEnergyDrain(0.34);
        overdrive.setStaminaDrain(1.0);
        overdrive.setAttackSpeed(1.0);
        overdrive.setHairColor("");
        overdrive.setEye1Color("");
        overdrive.setEye2Color("");
        overdrive.setAuraColor("#FFFD99");
		overdrive.setHasLightnings(true);
		overdrive.setLightningColor("#E6F2F5");
        overdrive.setBodyColor1("");
        overdrive.setBodyColor2("");
        overdrive.setBodyColor3("");
		overdrive.setHairType("ssj");
        overdrive.setForcedHairCode("");
        setDefaultMasteryValues(overdrive);
        overdrive.setKaiokenStackable(true);
        overdrive.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData solaris = new FormConfig.FormData();
        solaris.setName(HumanForms.SOLARIS);
        solaris.setUnlockOnSkillLevel(4);
        solaris.setCustomModel("");
        solaris.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        solaris.setStrMultiplier(3.0);
        solaris.setSkpMultiplier(3.35);
        solaris.setStmMultiplier(1.0);
        solaris.setDefMultiplier(2.5);
        solaris.setVitMultiplier(1.0);
        solaris.setPwrMultiplier(2.65);
        solaris.setEneMultiplier(1.0);
        solaris.setSpeedMultiplier(1.0);
        solaris.setEnergyDrain(0.22);
        solaris.setStaminaDrain(1.0);
        solaris.setAttackSpeed(1.0);
        solaris.setHairColor("");
        solaris.setEye1Color("");
        solaris.setEye2Color("");
        solaris.setAuraColor("");
		solaris.setHasLightnings(false);
		solaris.setLightningColor("");
        solaris.setBodyColor1("");
        solaris.setBodyColor2("");
        solaris.setBodyColor3("");
		solaris.setHairType("ssj");
        solaris.setForcedHairCode("");
        setDefaultMasteryValues(solaris);
        solaris.setKaiokenStackable(true);
        solaris.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> humanFormData = new LinkedHashMap<>();
        humanFormData.put(HumanForms.BUFFED, buffed);
        humanFormData.put(HumanForms.FULLPOWER, fullPower);
        humanFormData.put(HumanForms.OVERDRIVE, overdrive);
        //humanFormData.put(HumanForms.SOLARIS, solaris);
        humanForms.setForms(humanFormData);

        forms.put(HumanForms.GROUP_SUPERFORMS, humanForms);

        Path humanPath = formsPath.resolve(HumanForms.GROUP_SUPERFORMS + ".json");
        loader.saveConfig(humanPath, humanForms);
        LogUtil.info(Env.COMMON, "Default Human forms created");

        createAndroidForms(formsPath, forms);
	}

    private void createAndroidForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig androidForms = new FormConfig();
        androidForms.setGroupName(HumanForms.GROUP_ANDROIDFORMS);
        androidForms.setFormType("android");

        FormConfig.FormData androidBase = new FormConfig.FormData();
        androidBase.setName(HumanForms.ANDROID_BASE);
        androidBase.setUnlockOnSkillLevel(0);
        androidBase.setCustomModel("");
        androidBase.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        androidBase.setStrMultiplier(1.45);
        androidBase.setSkpMultiplier(1.35);
        androidBase.setStmMultiplier(1.0);
        androidBase.setDefMultiplier(1.25);
        androidBase.setVitMultiplier(1.0);
        androidBase.setPwrMultiplier(1.75);
        androidBase.setEneMultiplier(1.0);
        androidBase.setSpeedMultiplier(1.0);
        androidBase.setEnergyDrain(0.0);
        androidBase.setStaminaDrain(1.0);
        androidBase.setAttackSpeed(1.0);
        androidBase.setHairColor("");
        androidBase.setEye1Color("");
        androidBase.setEye2Color("");
        androidBase.setAuraColor("");
        androidBase.setHasLightnings(false);
        androidBase.setLightningColor("");
        androidBase.setBodyColor1("");
        androidBase.setBodyColor2("");
        androidBase.setBodyColor3("");
		androidBase.setHairType("base");
        androidBase.setForcedHairCode("");
        setDefaultMasteryValues(androidBase);
        androidBase.setKaiokenStackable(false);
        androidBase.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superAndroid = new FormConfig.FormData();
        superAndroid.setName(HumanForms.SUPER_ANDROID);
        superAndroid.setUnlockOnSkillLevel(1);
        superAndroid.setCustomModel("");
        superAndroid.setModelScaling(new float[]{1.05f, 1.05f, 1.05f});
        superAndroid.setStrMultiplier(2.15);
        superAndroid.setSkpMultiplier(2.0);
        superAndroid.setStmMultiplier(1.0);
        superAndroid.setDefMultiplier(1.65);
        superAndroid.setVitMultiplier(1.0);
        superAndroid.setPwrMultiplier(2.65);
        superAndroid.setEneMultiplier(1.0);
        superAndroid.setSpeedMultiplier(1.0);
        superAndroid.setEnergyDrain(0.0);
        superAndroid.setStaminaDrain(1.0);
        superAndroid.setAttackSpeed(1.0);
        superAndroid.setHairColor("");
        superAndroid.setEye1Color("");
        superAndroid.setEye2Color("");
        superAndroid.setAuraColor("");
        superAndroid.setHasLightnings(false);
        superAndroid.setLightningColor("");
        superAndroid.setBodyColor1("");
        superAndroid.setBodyColor2("");
        superAndroid.setBodyColor3("");
		superAndroid.setHairType("ssj");
        superAndroid.setForcedHairCode("");
        setDefaultMasteryValues(superAndroid);
        superAndroid.setKaiokenStackable(false);
        superAndroid.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fusedAndroid = new FormConfig.FormData();
        fusedAndroid.setName(HumanForms.FUSED_ANDROID);
        fusedAndroid.setUnlockOnSkillLevel(2);
        fusedAndroid.setCustomModel("");
        fusedAndroid.setModelScaling(new float[]{1.4f, 1.3f, 1.4f});
        fusedAndroid.setStrMultiplier(2.85);
        fusedAndroid.setSkpMultiplier(2.65);
        fusedAndroid.setStmMultiplier(1.0);
        fusedAndroid.setDefMultiplier(2.15);
        fusedAndroid.setVitMultiplier(1.0);
        fusedAndroid.setPwrMultiplier(3.5);
        fusedAndroid.setEneMultiplier(1.0);
        fusedAndroid.setSpeedMultiplier(1.0);
        fusedAndroid.setEnergyDrain(0.0);
        fusedAndroid.setStaminaDrain(2.5);
        fusedAndroid.setAttackSpeed(0.85);
        fusedAndroid.setHairColor("#E65332");
        fusedAndroid.setEye1Color("#FFFFFF");
        fusedAndroid.setEye2Color("#FFFFFF");
        fusedAndroid.setAuraColor("");
        fusedAndroid.setHasLightnings(true);
        fusedAndroid.setLightningColor("#E63232");
        fusedAndroid.setBodyColor1("#4D9AE8");
        fusedAndroid.setBodyColor2("");
        fusedAndroid.setBodyColor3("");
		fusedAndroid.setHairType("ssj");
        fusedAndroid.setForcedHairCode("");
        setDefaultMasteryValues(fusedAndroid);
        fusedAndroid.setKaiokenStackable(false);
        fusedAndroid.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> androidFormData = new LinkedHashMap<>();
        androidFormData.put(HumanForms.ANDROID_BASE, androidBase);
        androidFormData.put(HumanForms.SUPER_ANDROID, superAndroid);
        androidFormData.put(HumanForms.FUSED_ANDROID, fusedAndroid);
        androidForms.setForms(androidFormData);

        forms.put(HumanForms.GROUP_ANDROIDFORMS, androidForms);

        Path androidPath = formsPath.resolve(HumanForms.GROUP_ANDROIDFORMS + ".json");
        loader.saveConfig(androidPath, androidForms);
        LogUtil.info(Env.COMMON, "Default Android forms created for Humans");
    }

    private void createSaiyanForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig oozaruForms = new FormConfig();
        oozaruForms.setGroupName(SaiyanForms.GROUP_OOZARU);
        oozaruForms.setFormType("super");

        FormConfig.FormData oozaru = new FormConfig.FormData();
        oozaru.setName(SaiyanForms.OOZARU);
        oozaru.setUnlockOnSkillLevel(0);
        oozaru.setCustomModel("oozaru");
        oozaru.setModelScaling(new float[]{3.8f, 3.8f, 3.8f});
        oozaru.setStrMultiplier(1.2);
        oozaru.setSkpMultiplier(1.2);
        oozaru.setStmMultiplier(1.0);
        oozaru.setDefMultiplier(1.1);
        oozaru.setVitMultiplier(1.0);
        oozaru.setPwrMultiplier(1.2);
        oozaru.setEneMultiplier(1.0);
        oozaru.setSpeedMultiplier(0.8);
        oozaru.setEnergyDrain(0.05);
        oozaru.setStaminaDrain(1.2);
        oozaru.setAttackSpeed(0.9);
        oozaru.setHairColor("");
        oozaru.setEye1Color("");
        oozaru.setEye2Color("");
        oozaru.setAuraColor("");
		oozaru.setHasLightnings(false);
		oozaru.setLightningColor("");
        oozaru.setBodyColor1("");
        oozaru.setBodyColor2("");
        oozaru.setBodyColor3("");
		oozaru.setHairType("base");
        oozaru.setForcedHairCode("");
        setDefaultMasteryValues(oozaru);
		oozaru.setKaiokenStackable(true);
		oozaru.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData goldenOozaru = new FormConfig.FormData();
        goldenOozaru.setName(SaiyanForms.GOLDEN_OOZARU);
        goldenOozaru.setUnlockOnSkillLevel(7);
        goldenOozaru.setCustomModel("oozaru");
        goldenOozaru.setHairColor("#FFD700");
        goldenOozaru.setAuraColor("#FFD700");
        goldenOozaru.setModelScaling(new float[]{3.8f, 3.8f, 3.8f});
        goldenOozaru.setStrMultiplier(3.0);
        goldenOozaru.setSkpMultiplier(3.0);
        goldenOozaru.setStmMultiplier(1.0);
        goldenOozaru.setDefMultiplier(1.9);
        goldenOozaru.setVitMultiplier(1.0);
        goldenOozaru.setPwrMultiplier(3.0);
        goldenOozaru.setEneMultiplier(1.0);
        goldenOozaru.setSpeedMultiplier(0.85);
        goldenOozaru.setEnergyDrain(0.24);
        goldenOozaru.setStaminaDrain(1.3);
        goldenOozaru.setAttackSpeed(1.0);
        goldenOozaru.setEye1Color("");
        goldenOozaru.setEye2Color("");
		goldenOozaru.setHasLightnings(false);
		goldenOozaru.setLightningColor("");
        goldenOozaru.setBodyColor1("");
        goldenOozaru.setBodyColor2("");
        goldenOozaru.setBodyColor3("");
		goldenOozaru.setHairType("base");
        goldenOozaru.setForcedHairCode("");
        setDefaultMasteryValues(goldenOozaru);
		goldenOozaru.setKaiokenStackable(false);
		goldenOozaru.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssj4 = new FormConfig.FormData();
        ssj4.setName(SaiyanForms.SUPER_SAIYAN_4);
        ssj4.setUnlockOnSkillLevel(7);
        ssj4.setCustomModel("");
        ssj4.setHairColor("#000000");
        ssj4.setEye1Color("#FFD700");
        ssj4.setEye2Color("#FFD700");
        ssj4.setAuraColor("#FF0000");
		ssj4.setHasLightnings(false);
		ssj4.setLightningColor("");
        ssj4.setBodyColor1("");
        ssj4.setBodyColor2("");
        ssj4.setBodyColor3("");
        ssj4.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssj4.setStrMultiplier(4.5);
        ssj4.setSkpMultiplier(4.5);
        ssj4.setStmMultiplier(1.0);
        ssj4.setDefMultiplier(2.5);
        ssj4.setVitMultiplier(1.0);
        ssj4.setPwrMultiplier(4.5);
        ssj4.setEneMultiplier(1.0);
        ssj4.setSpeedMultiplier(1.0);
        ssj4.setEnergyDrain(0.22);
        ssj4.setStaminaDrain(1.0);
        ssj4.setAttackSpeed(1.0);
		ssj4.setHairType("base");
        ssj4.setForcedHairCode("");
        setDefaultMasteryValues(ssj4);
		ssj4.setKaiokenStackable(false);
		ssj4.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> oozaruFormData = new LinkedHashMap<>();
        oozaruFormData.put(SaiyanForms.OOZARU, oozaru);
        oozaruFormData.put(SaiyanForms.GOLDEN_OOZARU, goldenOozaru);
        //oozaruFormData.put(SaiyanForms.SUPER_SAIYAN_4, ssj4);
        oozaruForms.setForms(oozaruFormData);

        FormConfig ssGrades = new FormConfig();
        ssGrades.setGroupName(SaiyanForms.GROUP_SSGRADES);
        ssGrades.setFormType("super");

        FormConfig.FormData ssj1 = new FormConfig.FormData();
        ssj1.setName(SaiyanForms.SUPER_SAIYAN);
        ssj1.setUnlockOnSkillLevel(1);
        ssj1.setCustomModel("");
        ssj1.setHairColor("#FFEDB3");
        ssj1.setEye1Color("#00FFFF");
        ssj1.setEye2Color("#00FFFF");
        ssj1.setAuraColor("#FFD700");
		ssj1.setHasLightnings(false);
		ssj1.setLightningColor("");
        ssj1.setBodyColor1("");
        ssj1.setBodyColor2("");
        ssj1.setBodyColor3("");
        ssj1.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssj1.setStrMultiplier(1.5);
        ssj1.setSkpMultiplier(1.5);
        ssj1.setStmMultiplier(1.0);
        ssj1.setDefMultiplier(1.25);
        ssj1.setVitMultiplier(1.0);
        ssj1.setPwrMultiplier(1.5);
        ssj1.setEneMultiplier(1.0);
        ssj1.setSpeedMultiplier(1.0);
        ssj1.setEnergyDrain(0.08);
        ssj1.setStaminaDrain(1.0);
        ssj1.setAttackSpeed(1.0);
		ssj1.setHairType("ssj");
        ssj1.setForcedHairCode("");
        setDefaultMasteryValues(ssj1);
        ssj1.setKaiokenStackable(true);
        ssj1.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssg2 = new FormConfig.FormData();
        ssg2.setName(SaiyanForms.SUPER_SAIYAN_GRADE_2);
        ssg2.setUnlockOnSkillLevel(2);
        ssg2.setCustomModel("");
        ssg2.setHairColor("#FFEDB3");
        ssg2.setEye1Color("#00FFFF");
        ssg2.setEye2Color("#00FFFF");
        ssg2.setAuraColor("#FFD700");
		ssg2.setHasLightnings(false);
		ssg2.setLightningColor("");
        ssg2.setBodyColor1("");
        ssg2.setBodyColor2("");
        ssg2.setBodyColor3("");
        ssg2.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        ssg2.setStrMultiplier(1.75);
        ssg2.setSkpMultiplier(1.75);
        ssg2.setStmMultiplier(1.0);
        ssg2.setDefMultiplier(1.4);
        ssg2.setVitMultiplier(1.0);
        ssg2.setPwrMultiplier(1.75);
        ssg2.setEneMultiplier(1.0);
        ssg2.setSpeedMultiplier(0.9);
        ssg2.setEnergyDrain(0.12);
        ssg2.setStaminaDrain(1.3);
        ssg2.setAttackSpeed(1.0);
		ssg2.setHairType("ssj");
        ssg2.setForcedHairCode("");
        setDefaultMasteryValues(ssg2);
        ssg2.setKaiokenStackable(true);
        ssg2.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssg3 = new FormConfig.FormData();
        ssg3.setName(SaiyanForms.SUPER_SAIYAN_GRADE_3);
        ssg3.setUnlockOnSkillLevel(3);
        ssg3.setCustomModel("");
        ssg3.setHairColor("#FFEDB3");
        ssg3.setEye1Color("#00FFFF");
        ssg3.setEye2Color("#00FFFF");
        ssg3.setAuraColor("#FFD700");
		ssg3.setHasLightnings(false);
		ssg3.setLightningColor("");
        ssg3.setBodyColor1("");
        ssg3.setBodyColor2("");
        ssg3.setBodyColor3("");
        ssg3.setModelScaling(new float[]{1.2f, 1.1f, 1.2f});
        ssg3.setStrMultiplier(2.75);
        ssg3.setSkpMultiplier(2.75);
        ssg3.setStmMultiplier(1.0);
        ssg3.setDefMultiplier(1.8);
        ssg3.setVitMultiplier(1.0);
        ssg3.setPwrMultiplier(2.75);
        ssg3.setEneMultiplier(1.0);
        ssg3.setSpeedMultiplier(0.7);
        ssg3.setEnergyDrain(0.28);
        ssg3.setStaminaDrain(3.5);
        ssg3.setAttackSpeed(0.75);
		ssg3.setHairType("ssj");
        ssg3.setForcedHairCode("");
        setDefaultMasteryValues(ssg3);
        ssg3.setKaiokenStackable(true);
        ssg3.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> ssGradeForms = new LinkedHashMap<>();
        ssGradeForms.put(SaiyanForms.SUPER_SAIYAN, ssj1);
        ssGradeForms.put(SaiyanForms.SUPER_SAIYAN_GRADE_2, ssg2);
        ssGradeForms.put(SaiyanForms.SUPER_SAIYAN_GRADE_3, ssg3);
        ssGrades.setForms(ssGradeForms);

        FormConfig superSaiyan = new FormConfig();
        superSaiyan.setGroupName(SaiyanForms.GROUP_SUPERSAIYAN);
        superSaiyan.setFormType("super");

        FormConfig.FormData ssj1Mastered = new FormConfig.FormData();
        ssj1Mastered.setName(SaiyanForms.SUPER_SAIYAN_MASTERED);
        ssj1Mastered.setUnlockOnSkillLevel(4);
        ssj1Mastered.setCustomModel("");
        ssj1Mastered.setHairColor("#FFE89E");
        ssj1Mastered.setEye1Color("#00FFFF");
        ssj1Mastered.setEye2Color("#00FFFF");
        ssj1Mastered.setAuraColor("#FFD700");
		ssj1Mastered.setHasLightnings(false);
		ssj1Mastered.setLightningColor("");
        ssj1Mastered.setBodyColor1("");
        ssj1Mastered.setBodyColor2("");
        ssj1Mastered.setBodyColor3("");
        ssj1Mastered.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssj1Mastered.setStrMultiplier(1.75);
        ssj1Mastered.setSkpMultiplier(1.75);
        ssj1Mastered.setStmMultiplier(1.0);
        ssj1Mastered.setDefMultiplier(1.35);
        ssj1Mastered.setVitMultiplier(1.0);
        ssj1Mastered.setPwrMultiplier(1.75);
        ssj1Mastered.setEneMultiplier(1.0);
        ssj1Mastered.setSpeedMultiplier(1.0);
        ssj1Mastered.setEnergyDrain(0.03);
        ssj1Mastered.setStaminaDrain(1.0);
        ssj1Mastered.setAttackSpeed(1.0);
		ssj1Mastered.setHairType("ssj");
        ssj1Mastered.setForcedHairCode("");
        setDefaultMasteryValues(ssj1Mastered);
        ssj1Mastered.setKaiokenStackable(true);
        ssj1Mastered.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssj2 = new FormConfig.FormData();
        ssj2.setName(SaiyanForms.SUPER_SAIYAN_2);
        ssj2.setUnlockOnSkillLevel(5);
        ssj2.setCustomModel("");
        ssj2.setHairColor("#FFE89E");
        ssj2.setEye1Color("#00FFFF");
        ssj2.setEye2Color("#00FFFF");
        ssj2.setAuraColor("#FFD700");
		ssj2.setHasLightnings(true);
		ssj2.setLightningColor("#A1FFF9");
        ssj2.setBodyColor1("");
        ssj2.setBodyColor2("");
        ssj2.setBodyColor3("");
        ssj2.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssj2.setStrMultiplier(2.25);
        ssj2.setSkpMultiplier(2.25);
        ssj2.setStmMultiplier(1.0);
        ssj2.setDefMultiplier(1.65);
        ssj2.setVitMultiplier(1.0);
        ssj2.setPwrMultiplier(2.25);
        ssj2.setEneMultiplier(1.0);
        ssj2.setSpeedMultiplier(1.0);
        ssj2.setEnergyDrain(0.16);
        ssj2.setStaminaDrain(1.0);
        ssj2.setAttackSpeed(1.0);
		ssj2.setHairType("ssj");
        ssj2.setForcedHairCode("");
        setDefaultMasteryValues(ssj2);
        ssj2.setKaiokenStackable(true);
        ssj2.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ssj3 = new FormConfig.FormData();
        ssj3.setName(SaiyanForms.SUPER_SAIYAN_3);
        ssj3.setUnlockOnSkillLevel(6);
        ssj3.setCustomModel("");
        ssj3.setHairColor("#FFE89E");
        ssj3.setEye1Color("#00FFFF");
        ssj3.setEye2Color("#00FFFF");
        ssj3.setAuraColor("#FFD700");
		ssj3.setHasLightnings(true);
		ssj3.setLightningColor("#A1FFF9");
        ssj3.setBodyColor1("");
        ssj3.setBodyColor2("");
        ssj3.setBodyColor3("");
        ssj3.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssj3.setStrMultiplier(3.0);
        ssj3.setSkpMultiplier(3.0);
        ssj3.setStmMultiplier(1.0);
        ssj3.setDefMultiplier(2.15);
        ssj3.setVitMultiplier(1.0);
        ssj3.setPwrMultiplier(3.0);
        ssj3.setEneMultiplier(1.0);
        ssj3.setSpeedMultiplier(1.0);
        ssj3.setEnergyDrain(0.34);
        ssj3.setStaminaDrain(1.0);
        ssj3.setAttackSpeed(1.0);
		ssj3.setHairType("ssj3");
		ssj3.setForcedHairCode("");
        setDefaultMasteryValues(ssj3);
        ssj3.setKaiokenStackable(true);
        ssj3.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> superSaiyanForms = new LinkedHashMap<>();
        superSaiyanForms.put(SaiyanForms.SUPER_SAIYAN_MASTERED, ssj1Mastered);
        superSaiyanForms.put(SaiyanForms.SUPER_SAIYAN_2, ssj2);
        superSaiyanForms.put(SaiyanForms.SUPER_SAIYAN_3, ssj3);
        superSaiyan.setForms(superSaiyanForms);

        forms.put(SaiyanForms.OOZARU, oozaruForms);
        forms.put(SaiyanForms.GROUP_SSGRADES, ssGrades);
        forms.put(SaiyanForms.SUPER_SAIYAN, superSaiyan);

        // God Forms group
        FormConfig godForms = new FormConfig();
        godForms.setGroupName(SaiyanForms.GROUP_GOD);
        godForms.setFormType("god");

        FormConfig.FormData ssg = new FormConfig.FormData();
        ssg.setName(SaiyanForms.SUPER_SAIYAN_GOD);
        ssg.setUnlockOnSkillLevel(1);
        ssg.setCustomModel("");
        ssg.setHairColor("#FF0000");
        ssg.setEye1Color("#FF0000");
        ssg.setEye2Color("#FF0000");
        ssg.setAuraColor("#FF5100");
        ssg.setHasLightnings(false);
        ssg.setLightningColor("");
        ssg.setBodyColor1("");
        ssg.setBodyColor2("");
        ssg.setBodyColor3("");
        ssg.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssg.setStrMultiplier(3.5);
        ssg.setSkpMultiplier(3.5);
        ssg.setStmMultiplier(1.0);
        ssg.setDefMultiplier(2.5);
        ssg.setVitMultiplier(1.0);
        ssg.setPwrMultiplier(3.5);
        ssg.setEneMultiplier(1.0);
        ssg.setSpeedMultiplier(1.1);
        ssg.setEnergyDrain(0.20);
        ssg.setStaminaDrain(1.0);
        ssg.setAttackSpeed(1.0);
        ssg.setHairType("base");
        ssg.setForcedHairCode("");
        setDefaultMasteryValues(ssg);
        ssg.setKaiokenStackable(true);
        ssg.setKaiokenDrainMultiplier(2.5);

        FormConfig.FormData ssb = new FormConfig.FormData();
        ssb.setName(SaiyanForms.SUPER_SAIYAN_BLUE);
        ssb.setUnlockOnSkillLevel(3);
        ssb.setCustomModel("");
        ssb.setHairColor("#00BFFF");
        ssb.setEye1Color("#00BFFF");
        ssb.setEye2Color("#00BFFF");
        ssb.setAuraColor("#00BFFF");
        ssb.setHasLightnings(false);
        ssb.setLightningColor("");
        ssb.setBodyColor1("");
        ssb.setBodyColor2("");
        ssb.setBodyColor3("");
        ssb.setModelScaling(new float[]{0.9375f, 0.9375f, 0.9375f});
        ssb.setStrMultiplier(5.0);
        ssb.setSkpMultiplier(5.0);
        ssb.setStmMultiplier(1.0);
        ssb.setDefMultiplier(3.5);
        ssb.setVitMultiplier(1.0);
        ssb.setPwrMultiplier(5.0);
        ssb.setEneMultiplier(1.0);
        ssb.setSpeedMultiplier(1.15);
        ssb.setEnergyDrain(0.40);
        ssb.setStaminaDrain(1.0);
        ssb.setAttackSpeed(1.0);
        ssb.setHairType("ssj");
        ssb.setForcedHairCode("");
        setDefaultMasteryValues(ssb);
        ssb.setKaiokenStackable(true);
        ssb.setKaiokenDrainMultiplier(3.0);

        Map<String, FormConfig.FormData> godFormData = new LinkedHashMap<>();
        godFormData.put(SaiyanForms.SUPER_SAIYAN_GOD, ssg);
        godFormData.put(SaiyanForms.SUPER_SAIYAN_BLUE, ssb);
        godForms.setForms(godFormData);

        forms.put(SaiyanForms.GROUP_GOD, godForms);

        Path oozaruPath = formsPath.resolve(SaiyanForms.OOZARU + ".json");
        if (!Files.exists(oozaruPath)) loader.saveConfig(oozaruPath, oozaruForms);
        Path ssGradesPath = formsPath.resolve(SaiyanForms.GROUP_SSGRADES + ".json");
        if (!Files.exists(ssGradesPath)) loader.saveConfig(ssGradesPath, ssGrades);
        Path superSaiyanPath = formsPath.resolve(SaiyanForms.SUPER_SAIYAN + ".json");
        if (!Files.exists(superSaiyanPath)) loader.saveConfig(superSaiyanPath, superSaiyan);
        Path godFormsPath = formsPath.resolve(SaiyanForms.GROUP_GOD + ".json");
        if (!Files.exists(godFormsPath)) {
            loader.saveConfig(godFormsPath, godForms);
            forms.put(SaiyanForms.GROUP_GOD, godForms);
        }
        LogUtil.info(Env.COMMON, "Default Super Saiyan forms created");
    }

    private void createNamekianForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig namekianForms = new FormConfig();
        namekianForms.setGroupName(NamekianForms.GROUP_SUPERFORMS);
        namekianForms.setFormType("super");

        FormConfig.FormData giantForm = new FormConfig.FormData();
        giantForm.setName(NamekianForms.GIANT);
        giantForm.setUnlockOnSkillLevel(1);
        giantForm.setCustomModel("");
        giantForm.setModelScaling(new float[]{3.6f, 3.6f, 3.6f});
        giantForm.setStrMultiplier(1.5);
        giantForm.setSkpMultiplier(1.5);
        giantForm.setStmMultiplier(1.0);
        giantForm.setDefMultiplier(1.4);
        giantForm.setVitMultiplier(1.0);
        giantForm.setPwrMultiplier(1.5);
        giantForm.setEneMultiplier(1.0);
        giantForm.setSpeedMultiplier(1.0);
        giantForm.setEnergyDrain(0.09);
        giantForm.setStaminaDrain(1.0);
        giantForm.setAttackSpeed(1.0);
        giantForm.setHairColor("");
        giantForm.setEye1Color("");
        giantForm.setEye2Color("");
        giantForm.setAuraColor("");
		giantForm.setHasLightnings(false);
		giantForm.setLightningColor("");
        giantForm.setBodyColor1("");
        giantForm.setBodyColor2("");
        giantForm.setBodyColor3("");
		giantForm.setHairType("base");
        giantForm.setForcedHairCode("");
        setDefaultMasteryValues(giantForm);
        giantForm.setKaiokenStackable(true);
        giantForm.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fullPower = new FormConfig.FormData();
        fullPower.setName(NamekianForms.FULLPOWER);
        fullPower.setUnlockOnSkillLevel(2);
        fullPower.setCustomModel("");
        fullPower.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        fullPower.setStrMultiplier(2.25);
        fullPower.setSkpMultiplier(2.25);
        fullPower.setStmMultiplier(1.0);
        fullPower.setDefMultiplier(1.85);
        fullPower.setVitMultiplier(1.0);
        fullPower.setPwrMultiplier(2.25);
        fullPower.setEneMultiplier(1.0);
        fullPower.setSpeedMultiplier(1.0);
        fullPower.setEnergyDrain(0.18);
        fullPower.setStaminaDrain(1.0);
        fullPower.setAttackSpeed(1.0);
        fullPower.setHairColor("");
        fullPower.setEye1Color("");
        fullPower.setEye2Color("");
        fullPower.setAuraColor("");
		fullPower.setHasLightnings(false);
		fullPower.setLightningColor("");
        fullPower.setBodyColor1("");
        fullPower.setBodyColor2("");
        fullPower.setBodyColor3("");
		fullPower.setHairType("base");
        fullPower.setForcedHairCode("");
        setDefaultMasteryValues(fullPower);
        fullPower.setKaiokenStackable(true);
        fullPower.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superNamekian = new FormConfig.FormData();
        superNamekian.setName(NamekianForms.SUPER_NAMEKIAN);
        superNamekian.setUnlockOnSkillLevel(3);
        superNamekian.setCustomModel("");
        superNamekian.setAuraColor("#7FFF00");
		superNamekian.setHasLightnings(true);
		superNamekian.setLightningColor("#FFFFFF");
        superNamekian.setModelScaling(new float[]{1.05f, 1.05f, 1.05f});
        superNamekian.setStrMultiplier(3.0);
        superNamekian.setSkpMultiplier(3.0);
        superNamekian.setStmMultiplier(1.0);
        superNamekian.setDefMultiplier(2.35);
        superNamekian.setVitMultiplier(1.0);
        superNamekian.setPwrMultiplier(3.0);
        superNamekian.setEneMultiplier(1.0);
        superNamekian.setSpeedMultiplier(1.0);
        superNamekian.setEnergyDrain(0.27);
        superNamekian.setStaminaDrain(1.0);
        superNamekian.setAttackSpeed(1.0);
        superNamekian.setHairColor("");
        superNamekian.setEye1Color("");
        superNamekian.setEye2Color("");
        superNamekian.setBodyColor1("");
        superNamekian.setBodyColor2("");
        superNamekian.setBodyColor3("");
		superNamekian.setHairType("base");
        superNamekian.setForcedHairCode("");
        setDefaultMasteryValues(superNamekian);
        superNamekian.setKaiokenStackable(true);
        superNamekian.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> namekianFormData = new LinkedHashMap<>();
        namekianFormData.put(NamekianForms.GIANT, giantForm);
        namekianFormData.put(NamekianForms.FULLPOWER, fullPower);
        namekianFormData.put(NamekianForms.SUPER_NAMEKIAN, superNamekian);
        namekianForms.setForms(namekianFormData);

        forms.put(NamekianForms.GROUP_SUPERFORMS, namekianForms);

        Path namekianPath = formsPath.resolve(NamekianForms.GROUP_SUPERFORMS + ".json");
        loader.saveConfig(namekianPath, namekianForms);
        LogUtil.info(Env.COMMON, "Default Namekian forms created");
    }

    private void createFrostDemonForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig frostForms = new FormConfig();
        frostForms.setGroupName(FrostDemonForms.GROUP_EVOLUTIONFORMS);
        frostForms.setFormType("super");

        FormConfig.FormData second = new FormConfig.FormData();
        second.setName(FrostDemonForms.SECOND_FORM);
        second.setUnlockOnSkillLevel(1);
        second.setCustomModel("");
        second.setModelScaling(new float[]{1.3f, 1.3f, 1.3f});
        second.setStrMultiplier(1.5);
        second.setSkpMultiplier(1.5);
        second.setStmMultiplier(1.0);
        second.setDefMultiplier(1.25);
        second.setVitMultiplier(1.0);
        second.setPwrMultiplier(1.5);
        second.setEneMultiplier(1.0);
        second.setSpeedMultiplier(1.0);
        second.setEnergyDrain(0.0);
        second.setStaminaDrain(1.0);
        second.setAttackSpeed(1.0);
        second.setHairColor("");
        second.setEye1Color("");
        second.setEye2Color("");
        second.setAuraColor("");
		second.setHasLightnings(false);
		second.setLightningColor("");
        second.setBodyColor1("");
        second.setBodyColor2("");
        second.setBodyColor3("");
		second.setHairType("base");
        second.setForcedHairCode("");
        setDefaultMasteryValues(second);
        second.setKaiokenStackable(true);
        second.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData third = new FormConfig.FormData();
        third.setName(FrostDemonForms.THIRD_FORM);
        third.setUnlockOnSkillLevel(2);
        third.setCustomModel("frostdemon_third");
        third.setModelScaling(new float[]{1.4f, 1.4f, 1.4f});
        third.setStrMultiplier(1.75);
        third.setSkpMultiplier(1.75);
        third.setStmMultiplier(1.0);
        third.setDefMultiplier(1.65);
        third.setVitMultiplier(1.0);
        third.setPwrMultiplier(1.75);
        third.setEneMultiplier(1.0);
        third.setSpeedMultiplier(1.0);
        third.setEnergyDrain(0.0);
        third.setStaminaDrain(1.0);
        third.setAttackSpeed(1.0);
        third.setHairColor("");
        third.setEye1Color("");
        third.setEye2Color("");
        third.setAuraColor("");
		third.setHasLightnings(false);
		third.setLightningColor("");
        third.setBodyColor1("");
        third.setBodyColor2("");
        third.setBodyColor3("");
		third.setHairType("base");
        third.setForcedHairCode("");
        setDefaultMasteryValues(third);
        third.setKaiokenStackable(true);
        third.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData finalForm = new FormConfig.FormData();
        finalForm.setName(FrostDemonForms.FINAL_FORM);
        finalForm.setUnlockOnSkillLevel(3);
        finalForm.setCustomModel("");
        finalForm.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        finalForm.setStrMultiplier(2.25);
        finalForm.setSkpMultiplier(2.25);
        finalForm.setStmMultiplier(1.0);
        finalForm.setDefMultiplier(1.85);
        finalForm.setVitMultiplier(1.0);
        finalForm.setPwrMultiplier(2.25);
        finalForm.setEneMultiplier(1.0);
        finalForm.setSpeedMultiplier(1.0);
        finalForm.setEnergyDrain(0.0);
        finalForm.setStaminaDrain(1.0);
        finalForm.setAttackSpeed(1.0);
        finalForm.setHairColor("");
        finalForm.setEye1Color("");
        finalForm.setEye2Color("");
        finalForm.setAuraColor("");
		finalForm.setHasLightnings(false);
		finalForm.setLightningColor("");
        finalForm.setBodyColor1("");
        finalForm.setBodyColor2("");
        finalForm.setBodyColor3("");
		finalForm.setHairType("base");
        finalForm.setForcedHairCode("");
        setDefaultMasteryValues(finalForm);
        finalForm.setKaiokenStackable(true);
        finalForm.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData fullPower = new FormConfig.FormData();
        fullPower.setName(FrostDemonForms.FULLPOWER);
        fullPower.setUnlockOnSkillLevel(4);
        fullPower.setCustomModel("");
        fullPower.setModelScaling(new float[]{1.3f, 1.2f, 1.3f});
        fullPower.setStrMultiplier(2.75);
        fullPower.setSkpMultiplier(2.75);
        fullPower.setStmMultiplier(1.0);
        fullPower.setDefMultiplier(2.15);
        fullPower.setVitMultiplier(1.0);
        fullPower.setPwrMultiplier(2.75);
        fullPower.setEneMultiplier(1.0);
        fullPower.setSpeedMultiplier(1.0);
        fullPower.setEnergyDrain(0.22);
        fullPower.setStaminaDrain(2.5);
        fullPower.setAttackSpeed(0.75);
        fullPower.setHairColor("");
        fullPower.setEye1Color("");
        fullPower.setEye2Color("");
        fullPower.setAuraColor("");
		fullPower.setHasLightnings(false);
		fullPower.setLightningColor("#F02B16");
        fullPower.setBodyColor1("");
        fullPower.setBodyColor2("");
        fullPower.setBodyColor3("");
		fullPower.setHairType("base");
        fullPower.setForcedHairCode("");
        setDefaultMasteryValues(fullPower);
        fullPower.setKaiokenStackable(true);
        fullPower.setKaiokenDrainMultiplier(2.0);

		FormConfig.FormData fifthForm = new FormConfig.FormData();
		fifthForm.setName(FrostDemonForms.FIFTH_FORM);
		fifthForm.setUnlockOnSkillLevel(5);
		fifthForm.setCustomModel("frostdemon_fifth");
		fifthForm.setModelScaling(new float[]{1.4f, 1.3f, 1.4f});
		fifthForm.setStrMultiplier(3.0);
		fifthForm.setSkpMultiplier(3.0);
		fifthForm.setStmMultiplier(1.0);
		fifthForm.setDefMultiplier(2.35);
		fifthForm.setVitMultiplier(1.0);
		fifthForm.setPwrMultiplier(3.0);
		fifthForm.setEneMultiplier(1.0);
		fifthForm.setSpeedMultiplier(1.0);
		fifthForm.setEnergyDrain(0.18);
		fifthForm.setStaminaDrain(1.0);
		fifthForm.setAttackSpeed(1.0);
		fifthForm.setHairColor("");
		fifthForm.setEye1Color("#D91E1E");
		fifthForm.setEye2Color("#D91E1E");
		fifthForm.setAuraColor("");
		fifthForm.setHasLightnings(true);
		fifthForm.setLightningColor("#F02B16");
		fifthForm.setBodyColor1("");
		fifthForm.setBodyColor2("");
		fifthForm.setBodyColor3("");
		fifthForm.setHairType("base");
		fifthForm.setForcedHairCode("");
		setDefaultMasteryValues(fifthForm);
		fifthForm.setKaiokenStackable(true);
		fifthForm.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> frostFormData = new LinkedHashMap<>();
        frostFormData.put(FrostDemonForms.SECOND_FORM, second);
        frostFormData.put(FrostDemonForms.THIRD_FORM, third);
        frostFormData.put(FrostDemonForms.FINAL_FORM, finalForm);
        frostFormData.put(FrostDemonForms.FULLPOWER, fullPower);
		frostFormData.put(FrostDemonForms.FIFTH_FORM, fifthForm);
        frostForms.setForms(frostFormData);

        forms.put(FrostDemonForms.GROUP_EVOLUTIONFORMS, frostForms);

        Path frostPath = formsPath.resolve(FrostDemonForms.GROUP_EVOLUTIONFORMS + ".json");
        loader.saveConfig(frostPath, frostForms);
        LogUtil.info(Env.COMMON, "Default Frost Demon forms created");
    }

    private void createMajinForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig majinForms = new FormConfig();
        majinForms.setGroupName(MajinForms.GROUP_PUREFORMS);
        majinForms.setFormType("super");

        FormConfig.FormData kid = new FormConfig.FormData();
        kid.setName(MajinForms.KID);
        kid.setUnlockOnSkillLevel(1);
        kid.setCustomModel("human_slim");
        kid.setModelScaling(new float[]{0.7f, 0.7f, 0.7f});
        kid.setStrMultiplier(1.5);
        kid.setSkpMultiplier(1.5);
        kid.setStmMultiplier(1.0);
        kid.setDefMultiplier(1.25);
        kid.setVitMultiplier(1.0);
        kid.setPwrMultiplier(1.5);
        kid.setEneMultiplier(1.0);
        kid.setSpeedMultiplier(1.0);
        kid.setEnergyDrain(0.0);
        kid.setStaminaDrain(1.0);
        kid.setAttackSpeed(1.0);
        kid.setHairColor("");
        kid.setEye1Color("");
        kid.setEye2Color("");
        kid.setAuraColor("");
		kid.setHasLightnings(false);
		kid.setLightningColor("");
        kid.setBodyColor1("");
        kid.setBodyColor2("");
        kid.setBodyColor3("");
		kid.setHairType("base");
        kid.setForcedHairCode("");
        setDefaultMasteryValues(kid);
        kid.setKaiokenStackable(true);
        kid.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData evil = new FormConfig.FormData();
        evil.setName(MajinForms.EVIL);
        evil.setUnlockOnSkillLevel(2);
        evil.setCustomModel("");
        evil.setModelScaling(new float[]{0.9f, 1.0f, 0.9f});
        evil.setStrMultiplier(1.75);
        evil.setSkpMultiplier(1.75);
        evil.setStmMultiplier(1.0);
        evil.setDefMultiplier(1.65);
        evil.setVitMultiplier(1.0);
        evil.setPwrMultiplier(1.75);
        evil.setEneMultiplier(1.0);
        evil.setSpeedMultiplier(1.0);
        evil.setEnergyDrain(0.0);
        evil.setStaminaDrain(1.0);
        evil.setAttackSpeed(1.0);
        evil.setHairColor("#917979");
        evil.setEye1Color("#F52746");
        evil.setEye2Color("#F52746");
        evil.setAuraColor("");
		evil.setHasLightnings(false);
		evil.setLightningColor("");
        evil.setBodyColor1("#917979");
        evil.setBodyColor2("#917979");
        evil.setBodyColor3("#917979");
		evil.setHairType("base");
        evil.setForcedHairCode("");
        setDefaultMasteryValues(evil);
        evil.setKaiokenStackable(true);
        evil.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superForm = new FormConfig.FormData();
        superForm.setName(MajinForms.SUPER);
        superForm.setUnlockOnSkillLevel(3);
        superForm.setCustomModel("");
        superForm.setModelScaling(new float[]{1.0f, 1.0f, 1.0f});
        superForm.setStrMultiplier(2.25);
        superForm.setSkpMultiplier(2.25);
        superForm.setStmMultiplier(1.0);
        superForm.setDefMultiplier(2.15);
        superForm.setVitMultiplier(1.0);
        superForm.setPwrMultiplier(2.25);
        superForm.setEneMultiplier(1.0);
        superForm.setSpeedMultiplier(1.0);
        superForm.setEnergyDrain(0.0);
        superForm.setStaminaDrain(1.0);
        superForm.setAttackSpeed(1.0);
        superForm.setHairColor("");
        superForm.setEye1Color("");
        superForm.setEye2Color("");
        superForm.setAuraColor("");
		superForm.setHasLightnings(false);
		superForm.setLightningColor("");
        superForm.setBodyColor1("");
        superForm.setBodyColor2("");
        superForm.setBodyColor3("");
		superForm.setHairType("base");
        superForm.setForcedHairCode("");
        setDefaultMasteryValues(superForm);
        superForm.setKaiokenStackable(true);
        superForm.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData ultra = new FormConfig.FormData();
        ultra.setName(MajinForms.ULTRA);
        ultra.setUnlockOnSkillLevel(4);
        ultra.setCustomModel("");
        ultra.setModelScaling(new float[]{1.3f, 1.2f, 1.3f});
        ultra.setStrMultiplier(3.0);
        ultra.setSkpMultiplier(3.0);
        ultra.setStmMultiplier(1.0);
        ultra.setDefMultiplier(2.5);
        ultra.setVitMultiplier(1.0);
        ultra.setPwrMultiplier(3.0);
        ultra.setEneMultiplier(1.0);
        ultra.setSpeedMultiplier(1.0);
        ultra.setEnergyDrain(0.22);
        ultra.setStaminaDrain(3.5);
        ultra.setAttackSpeed(1.0);
        ultra.setHairColor("");
        ultra.setEye1Color("");
        ultra.setEye2Color("");
        ultra.setAuraColor("");
		ultra.setHasLightnings(true);
		ultra.setLightningColor("#F02B16");
        ultra.setBodyColor1("");
        ultra.setBodyColor2("");
        ultra.setBodyColor3("");
		ultra.setHairType("base");
        ultra.setForcedHairCode("");
        setDefaultMasteryValues(ultra);
        ultra.setKaiokenStackable(true);
        ultra.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> majinFormData = new LinkedHashMap<>();
        majinFormData.put(MajinForms.KID, kid);
        majinFormData.put(MajinForms.EVIL, evil);
        majinFormData.put(MajinForms.SUPER, superForm);
        majinFormData.put(MajinForms.ULTRA, ultra);
        majinForms.setForms(majinFormData);

        forms.put(MajinForms.GROUP_PUREFORMS, majinForms);

        Path majinPath = formsPath.resolve(MajinForms.GROUP_PUREFORMS + ".json");
        loader.saveConfig(majinPath, majinForms);
        LogUtil.info(Env.COMMON, "Default Majin forms created");
    }

    private void createBioAndroidForms(Path formsPath, Map<String, FormConfig> forms) throws IOException {
        FormConfig bioForms = new FormConfig();
        bioForms.setGroupName(BioAndroidForms.GROUP_BIOEVOLUTION);
        bioForms.setFormType("super");

        FormConfig.FormData semiPerfect = new FormConfig.FormData();
        semiPerfect.setName(BioAndroidForms.SEMI_PERFECT);
        semiPerfect.setUnlockOnSkillLevel(1);
        semiPerfect.setCustomModel("bioandroid_semi");
        semiPerfect.setModelScaling(new float[]{1.3f, 1.3f, 1.3f});
        semiPerfect.setStrMultiplier(1.5);
        semiPerfect.setSkpMultiplier(1.5);
        semiPerfect.setStmMultiplier(1.0);
        semiPerfect.setDefMultiplier(1.4);
        semiPerfect.setVitMultiplier(1.0);
        semiPerfect.setPwrMultiplier(1.5);
        semiPerfect.setEneMultiplier(1.0);
        semiPerfect.setSpeedMultiplier(1.0);
        semiPerfect.setEnergyDrain(0.0);
        semiPerfect.setStaminaDrain(1.0);
        semiPerfect.setAttackSpeed(1.0);
        semiPerfect.setHairColor("");
        semiPerfect.setEye1Color("");
        semiPerfect.setEye2Color("");
        semiPerfect.setAuraColor("");
		semiPerfect.setHasLightnings(false);
		semiPerfect.setLightningColor("");
        semiPerfect.setBodyColor1("");
        semiPerfect.setBodyColor2("");
        semiPerfect.setBodyColor3("");
		semiPerfect.setHairType("base");
        semiPerfect.setForcedHairCode("");
        setDefaultMasteryValues(semiPerfect);
        semiPerfect.setKaiokenStackable(true);
        semiPerfect.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData perfect = new FormConfig.FormData();
        perfect.setName(BioAndroidForms.PERFECT);
        perfect.setUnlockOnSkillLevel(2);
        perfect.setCustomModel("bioandroid_perfect");
        perfect.setModelScaling(new float[]{1.1f, 1.1f, 1.1f});
        perfect.setStrMultiplier(2.25);
        perfect.setSkpMultiplier(2.25);
        perfect.setStmMultiplier(1.0);
        perfect.setDefMultiplier(1.85);
        perfect.setVitMultiplier(1.0);
        perfect.setPwrMultiplier(2.25);
        perfect.setEneMultiplier(1.0);
        perfect.setSpeedMultiplier(1.0);
        perfect.setEnergyDrain(0.0);
        perfect.setStaminaDrain(1.0);
        perfect.setAttackSpeed(1.0);
        perfect.setHairColor("");
        perfect.setEye1Color("");
        perfect.setEye2Color("");
        perfect.setAuraColor("");
		perfect.setHasLightnings(false);
		perfect.setLightningColor("");
        perfect.setBodyColor1("");
        perfect.setBodyColor2("");
        perfect.setBodyColor3("");
		perfect.setHairType("base");
        perfect.setForcedHairCode("");
        setDefaultMasteryValues(perfect);
        perfect.setKaiokenStackable(true);
        perfect.setKaiokenDrainMultiplier(2.0);

        FormConfig.FormData superPerfect = new FormConfig.FormData();
        superPerfect.setName(BioAndroidForms.SUPER_PERFECT);
        superPerfect.setUnlockOnSkillLevel(3);
        superPerfect.setCustomModel("bioandroid_perfect");
        superPerfect.setModelScaling(new float[]{1.1f, 1.1f, 1.1f});
        superPerfect.setStrMultiplier(3.0);
        superPerfect.setSkpMultiplier(3.0);
        superPerfect.setStmMultiplier(1.0);
        superPerfect.setDefMultiplier(2.35);
        superPerfect.setVitMultiplier(1.0);
        superPerfect.setPwrMultiplier(3.0);
        superPerfect.setEneMultiplier(1.0);
        superPerfect.setSpeedMultiplier(1.0);
        superPerfect.setEnergyDrain(0.16);
        superPerfect.setStaminaDrain(1.0);
        superPerfect.setAttackSpeed(1.0);
        superPerfect.setHairColor("");
        superPerfect.setEye1Color("");
        superPerfect.setEye2Color("");
        superPerfect.setAuraColor("FFFF69");
		superPerfect.setHasLightnings(true);
		superPerfect.setLightningColor("#1AA1C7");
        superPerfect.setBodyColor1("");
        superPerfect.setBodyColor2("");
        superPerfect.setBodyColor3("");
		superPerfect.setHairType("base");
        superPerfect.setForcedHairCode("");
        setDefaultMasteryValues(superPerfect);
        superPerfect.setKaiokenStackable(true);
        superPerfect.setKaiokenDrainMultiplier(2.0);

        Map<String, FormConfig.FormData> bioFormData = new LinkedHashMap<>();
        bioFormData.put(BioAndroidForms.SEMI_PERFECT, semiPerfect);
        bioFormData.put(BioAndroidForms.PERFECT, perfect);
        bioFormData.put(BioAndroidForms.SUPER_PERFECT, superPerfect);
        bioForms.setForms(bioFormData);

        forms.put(BioAndroidForms.GROUP_BIOEVOLUTION, bioForms);

        Path bioAndroidPath = formsPath.resolve(BioAndroidForms.GROUP_BIOEVOLUTION + ".json");
        loader.saveConfig(bioAndroidPath, bioForms);
        LogUtil.info(Env.COMMON, "Default Bio Android forms created");
    }
}